apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-post-install-hook
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  restartPolicy: Never
  containers:
  - name: post-install-job
    image: busybox
    command: 
    - "/bin/sh"
    - "-c" 
    - |
      echo "Starting post-install hook for {{ .Release.Name }}"
      echo "Chart: {{ .Chart.Name }}"
      echo "Version: {{ .Chart.Version }}"
      echo "Sleeping for 20 seconds..."
      sleep 20
      echo "Post-install hook completed successfully" 